server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.13:3306/my_api
    username: mac
    password: 123456
  # redis 配置
  redis:
    port: 6379
    host: 192.168.5.13
    database: 0
    password: 123456
    timeout: 10000          #Redis 连接的超时时间
    lettuce: #使用 lettuce 连接池
      pool:
        max-active: 10      #连接池的最大连接数
        max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1          #连接池最小空闲连接
        max-idle: 10          #连接池最大空闲连接
